# Generated by Django 3.1.3 on 2020-12-06 20:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientBuy',
            fields=[
                ('buyerCode', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Код')),
                ('FIO', models.CharField(max_length=50, verbose_name='ФИО')),
                ('address', models.CharField(max_length=50, verbose_name='Адресс')),
                ('tel', models.IntegerField(verbose_name='Телефон')),
                ('passportCode', models.CharField(help_text='2 буквы и 7 цифр', max_length=9, verbose_name='Код поспорта')),
                ('passportNumber', models.CharField(help_text='14 символов', max_length=14, verbose_name='Индентификационный номер')),
            ],
            options={
                'verbose_name': 'Клиент покупатель',
                'verbose_name_plural': 'Клиенты покупатели',
            },
        ),
        migrations.CreateModel(
            name='ClientSell',
            fields=[
                ('sellerCode', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Код')),
                ('FIO', models.CharField(max_length=50, verbose_name='ФИО')),
                ('address', models.CharField(max_length=50, verbose_name='Адресс')),
                ('tel', models.IntegerField(verbose_name='Телефон')),
                ('passportCode', models.CharField(help_text='2 буквы и 7 цифр', max_length=9, verbose_name='Код поспорта')),
                ('passportNumber', models.CharField(help_text='14 символов', max_length=14, verbose_name='Индентификационный номер')),
            ],
            options={
                'verbose_name': 'Клиент продавец',
                'verbose_name_plural': 'Клиенты продавцы',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employeeCode', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Код')),
                ('FIO', models.CharField(max_length=50, verbose_name='ФИО')),
                ('post', models.CharField(max_length=50, verbose_name='Должность')),
                ('dateOfEmployment', models.DateField(verbose_name='Дата найма')),
                ('address', models.CharField(max_length=50, verbose_name='Адресс')),
                ('tel', models.IntegerField(verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='SelledProperty',
            fields=[
                ('applicationCode', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Код заявки')),
                ('dateOfOperation', models.DateField(verbose_name='Дата операции')),
                ('profit', models.IntegerField(verbose_name='Прибыль')),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.clientbuy', verbose_name='Покупатель')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.employees', verbose_name='Сотрудник')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.clientsell', verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Проданный объект',
                'verbose_name_plural': 'Проданные объекты',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('applicationCode', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Код заявки')),
                ('dateOfOrder', models.DateField(verbose_name='Дата составления заказа')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование объекта')),
                ('area', models.IntegerField(verbose_name='Площадь м2')),
                ('rooms', models.SmallIntegerField(verbose_name='Кол-во комнат')),
                ('street', models.CharField(max_length=50, verbose_name='Улица')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.clientsell', verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Недвижимость',
                'verbose_name_plural': 'Недвижимость',
            },
        ),
    ]
