# Generated by Django 3.1.3 on 2020-12-06 20:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selledproperty',
            name='contractCode',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Код договора'),
        ),
        migrations.AlterField(
            model_name='selledproperty',
            name='applicationCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.property', verbose_name='Код заявки'),
        ),
    ]
