# Generated by Django 3.1.3 on 2020-12-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Код')),
                ('FIO', models.CharField(max_length=50, verbose_name='ФИО')),
                ('post', models.CharField(max_length=50, verbose_name='Должность')),
                ('dateOfEmployment', models.DateField(verbose_name='Дата найма')),
                ('address', models.CharField(max_length=50, verbose_name='Адресс')),
                ('tel', models.IntegerField(verbose_name='Телефон')),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
