# Generated by Django 3.1.3 on 2020-12-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201206_2351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selledproperty',
            options={'verbose_name': 'Совершенная сделка', 'verbose_name_plural': 'Совершенные сделки'},
        ),
        migrations.AddField(
            model_name='property',
            name='ifSelled',
            field=models.BooleanField(default=False, verbose_name='Состояние продажи'),
        ),
    ]
