# Generated by Django 3.1.3 on 2020-12-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201207_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='street',
        ),
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.CharField(default=1, max_length=50, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientbuy',
            name='address',
            field=models.CharField(max_length=50, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='clientsell',
            name='address',
            field=models.CharField(max_length=50, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='address',
            field=models.CharField(max_length=50, verbose_name='Адрес'),
        ),
    ]
