# Generated by Django 3.1.3 on 2020-12-09 16:07

from django.db import migrations
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201207_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbuy',
            name='tel',
            field=main.models.IntegerRangeField(verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='clientsell',
            name='tel',
            field=main.models.IntegerRangeField(verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='tel',
            field=main.models.IntegerRangeField(verbose_name='Телефон'),
        ),
    ]
