# Generated by Django 3.1.3 on 2020-12-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201206_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbuy',
            name='FIO',
            field=models.CharField(max_length=50, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='clientbuy',
            name='address',
            field=models.CharField(max_length=50, verbose_name='Адресс'),
        ),
        migrations.AlterField(
            model_name='clientbuy',
            name='code',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='clientbuy',
            name='passportCode',
            field=models.CharField(max_length=50, verbose_name='Индентификационный номер'),
        ),
        migrations.AlterField(
            model_name='clientbuy',
            name='passportNumber',
            field=models.CharField(max_length=50, verbose_name='Код поспорта'),
        ),
        migrations.AlterField(
            model_name='clientbuy',
            name='tel',
            field=models.IntegerField(verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='clientsell',
            name='FIO',
            field=models.CharField(max_length=50, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='clientsell',
            name='address',
            field=models.CharField(max_length=50, verbose_name='Адресс'),
        ),
        migrations.AlterField(
            model_name='clientsell',
            name='code',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='clientsell',
            name='passportCode',
            field=models.CharField(max_length=50, verbose_name='Индентификационный номер'),
        ),
        migrations.AlterField(
            model_name='clientsell',
            name='passportNumber',
            field=models.CharField(max_length=50, verbose_name='Код поспорта'),
        ),
        migrations.AlterField(
            model_name='clientsell',
            name='tel',
            field=models.IntegerField(verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='FIO',
            field=models.CharField(max_length=50, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='address',
            field=models.CharField(max_length=50, verbose_name='Адресс'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='code',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='dateOfEmployment',
            field=models.DateField(verbose_name='Дата найма'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='post',
            field=models.CharField(max_length=50, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='tel',
            field=models.IntegerField(verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='property',
            name='applicationCode',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Код заявки'),
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.IntegerField(verbose_name='Площадь м2'),
        ),
        migrations.AlterField(
            model_name='property',
            name='dateOfOrder',
            field=models.DateField(verbose_name='Дата составления заказа'),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Наименование объекта'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='property',
            name='rooms',
            field=models.IntegerField(verbose_name='Кол-во комнат'),
        ),
        migrations.AlterField(
            model_name='property',
            name='sellerCode',
            field=models.IntegerField(verbose_name='Код продавца'),
        ),
        migrations.AlterField(
            model_name='property',
            name='street',
            field=models.CharField(max_length=50, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='selledproperty',
            name='applicationCode',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Код заявки'),
        ),
        migrations.AlterField(
            model_name='selledproperty',
            name='buyerCode',
            field=models.IntegerField(verbose_name='Код покупателя'),
        ),
        migrations.AlterField(
            model_name='selledproperty',
            name='dateOfOperation',
            field=models.DateField(verbose_name='Дата операции'),
        ),
        migrations.AlterField(
            model_name='selledproperty',
            name='dateOfOrder',
            field=models.DateField(verbose_name='Дата составления заказа'),
        ),
        migrations.AlterField(
            model_name='selledproperty',
            name='employeeCode',
            field=models.IntegerField(verbose_name='Код сотрудника'),
        ),
        migrations.AlterField(
            model_name='selledproperty',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Наименование объекта'),
        ),
        migrations.AlterField(
            model_name='selledproperty',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='selledproperty',
            name='profit',
            field=models.IntegerField(verbose_name='Прибыль'),
        ),
        migrations.AlterField(
            model_name='selledproperty',
            name='sellerCode',
            field=models.IntegerField(verbose_name='Код продавца'),
        ),
        migrations.AlterField(
            model_name='selledproperty',
            name='street',
            field=models.CharField(max_length=50, verbose_name='Улица'),
        ),
    ]
