# Generated by Django 3.1.3 on 2020-12-06 19:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201206_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientbuy',
            name='code',
        ),
        migrations.RemoveField(
            model_name='clientsell',
            name='code',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='code',
        ),
        migrations.AddField(
            model_name='clientbuy',
            name='buyerCode',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='clientsell',
            name='sellerCode',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='employees',
            name='employeeCode',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='property',
            name='applicationCode',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Код заявки'),
        ),
        migrations.AlterField(
            model_name='property',
            name='sellerCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.clientsell', verbose_name='Код продавца'),
        ),
        migrations.AlterField(
            model_name='selledproperty',
            name='applicationCode',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Код заявки'),
        ),
        migrations.AlterField(
            model_name='selledproperty',
            name='buyerCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.clientbuy', verbose_name='Код покупателя'),
        ),
        migrations.AlterField(
            model_name='selledproperty',
            name='employeeCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.employees', verbose_name='Код сотрудника'),
        ),
        migrations.AlterField(
            model_name='selledproperty',
            name='sellerCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.clientsell', verbose_name='Код продавца'),
        ),
    ]
