# Generated by Django 3.1.4 on 2020-12-09 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201209_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbuy',
            name='passportCode',
            field=models.CharField(help_text='2 буквы и 7 цифр', max_length=9, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Длинна = 9', regex='^.{9}$')], verbose_name='Код поспорта'),
        ),
        migrations.AlterField(
            model_name='clientbuy',
            name='passportNumber',
            field=models.CharField(help_text='14 символов', max_length=14, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Длинна = 14', regex='^.{14}$')], verbose_name='Индентификационный номер'),
        ),
        migrations.AlterField(
            model_name='clientsell',
            name='passportCode',
            field=models.CharField(help_text='2 буквы и 7 цифр', max_length=9, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Длинна = 9', regex='^.{9}$')], verbose_name='Код поспорта'),
        ),
        migrations.AlterField(
            model_name='clientsell',
            name='passportNumber',
            field=models.CharField(help_text='14 символов', max_length=14, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Длинна = 14', regex='^.{14}$')], verbose_name='Индентификационный номер'),
        ),
    ]
