# Generated by Django 3.1.3 on 2020-12-06 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201206_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='sellerCode',
        ),
        migrations.RemoveField(
            model_name='selledproperty',
            name='buyerCode',
        ),
        migrations.RemoveField(
            model_name='selledproperty',
            name='employeeCode',
        ),
        migrations.RemoveField(
            model_name='selledproperty',
            name='sellerCode',
        ),
        migrations.AddField(
            model_name='property',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.clientsell', verbose_name='Продавец'),
        ),
        migrations.AddField(
            model_name='selledproperty',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.clientbuy', verbose_name='Покупатель'),
        ),
        migrations.AddField(
            model_name='selledproperty',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.employees', verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='selledproperty',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.clientsell', verbose_name='Продавец'),
        ),
        migrations.AlterField(
            model_name='clientbuy',
            name='passportCode',
            field=models.CharField(max_length=14, verbose_name='Индентификационный номер'),
        ),
        migrations.AlterField(
            model_name='clientbuy',
            name='passportNumber',
            field=models.CharField(max_length=7, verbose_name='Код поспорта'),
        ),
        migrations.AlterField(
            model_name='clientsell',
            name='passportCode',
            field=models.CharField(max_length=14, verbose_name='Индентификационный номер'),
        ),
        migrations.AlterField(
            model_name='clientsell',
            name='passportNumber',
            field=models.CharField(max_length=7, verbose_name='Код поспорта'),
        ),
        migrations.AlterField(
            model_name='property',
            name='rooms',
            field=models.SmallIntegerField(verbose_name='Кол-во комнат'),
        ),
    ]
