# Generated by Django 3.1.4 on 2020-12-13 19:27

from django.db import migrations
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201210_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='area',
            field=main.models.IntegerRangeField(verbose_name='Площадь м2'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=main.models.IntegerRangeField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='property',
            name='rooms',
            field=main.models.IntegerRangeField(verbose_name='Кол-во комнат'),
        ),
    ]
