# Generated by Django 3.1.4 on 2020-12-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201213_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selledproperty',
            name='contractCode',
        ),
        migrations.AddField(
            model_name='selledproperty',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
