# Generated by Django 3.1.3 on 2020-12-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201206_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbuy',
            name='passportCode',
            field=models.CharField(help_text='7 символов', max_length=7, verbose_name='Код поспорта'),
        ),
        migrations.AlterField(
            model_name='clientbuy',
            name='passportNumber',
            field=models.CharField(help_text='14 символов', max_length=14, verbose_name='Индентификационный номер'),
        ),
        migrations.AlterField(
            model_name='clientsell',
            name='passportCode',
            field=models.CharField(help_text='7 символов', max_length=7, verbose_name='Код поспорта'),
        ),
        migrations.AlterField(
            model_name='clientsell',
            name='passportNumber',
            field=models.CharField(help_text='14 символов', max_length=14, verbose_name='Индентификационный номер'),
        ),
    ]
