# Generated by Django 3.1.4 on 2020-12-13 22:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201214_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selledproperty',
            name='id',
        ),
        migrations.AddField(
            model_name='selledproperty',
            name='contractCode',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Код договора'),
        ),
    ]
