# Generated by Django 3.1.4 on 2020-12-14 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201214_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selledproperty',
            name='applicationCode',
        ),
        migrations.RemoveField(
            model_name='selledproperty',
            name='seller',
        ),
        migrations.AddField(
            model_name='selledproperty',
            name='property_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='main.property'),
            preserve_default=False,
        ),
    ]
