# Generated by Django 3.1.4 on 2020-12-14 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201214_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selledproperty',
            name='property_ptr',
        ),
        migrations.AddField(
            model_name='selledproperty',
            name='applicationCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.property', verbose_name='Код заявки'),
        ),
        migrations.AddField(
            model_name='selledproperty',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.clientsell', verbose_name='Продавец'),
        ),
    ]
