# Generated by Django 3.1.4 on 2020-12-14 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201214_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selledproperty',
            name='seller',
        ),
    ]
