# Generated by Django 3.1.4 on 2020-12-14 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_selledproperty_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selledproperty',
            name='applicationCode',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.property', verbose_name='Код заявки'),
        ),
    ]
