# Generated by Django 3.1.4 on 2020-12-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20201214_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealsBackup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractCode', models.CharField(max_length=100, verbose_name='Код договора')),
                ('applicationCode', models.CharField(max_length=100, verbose_name='Код заявки')),
                ('dateOfOrder', models.DateField(verbose_name='Дата составления заказа')),
                ('dateOfOperation', models.DateField(verbose_name='Дата операции')),
                ('employee', models.CharField(max_length=50, verbose_name='Сотрудник')),
                ('buyer', models.CharField(max_length=50, verbose_name='Покупатель')),
                ('seller', models.CharField(max_length=50, verbose_name='Продавец')),
                ('price', models.CharField(max_length=50, verbose_name='Цена')),
                ('profit', models.CharField(max_length=50, verbose_name='Прибыль')),
            ],
        ),
    ]
